/**:
  ros__parameters:
    moveit_controller_manager:
        moveit_simple_controller_manager/MoveItSimpleControllerManager

    moveit_simple_controller_manager:
      controller_names:
        - left_ur_arm_controller
        - left_gripper_controller
        - right_ur_arm_controller
        - right_gripper_controller

      left_ur_arm_controller:
        type: FollowJointTrajectory
        action_ns: follow_joint_trajectory
        default: true
        joints:
          - left_shoulder_pan_joint
          - left_shoulder_lift_joint
          - left_elbow_joint
          - left_wrist_1_joint
          - left_wrist_2_joint
          - left_wrist_3_joint
        action_ns: follow_joint_trajectory
        default: true
      left_gripper_controller:
        type: GripperCommand
        joints:
          - left_robotiq_85_left_knuckle_joint
        action_ns: gripper_cmd
        default: true

      right_ur_arm_controller:
        type: FollowJointTrajectory
        action_ns: follow_joint_trajectory
        default: true
        joints:
          - right_shoulder_pan_joint
          - right_shoulder_lift_joint
          - right_elbow_joint
          - right_wrist_1_joint
          - right_wrist_2_joint
          - right_wrist_3_joint
        action_ns: follow_joint_trajectory
        default: true
      right_gripper_controller:
        type: GripperCommand
        joints:
          - right_robotiq_85_left_knuckle_joint
        action_ns: gripper_cmd
        default: true



