# These limits are used by MoveIt and augment/override the definitions in ur_description.
#
# While the robot does not inherently have any limits on joint accelerations (only on torques),
# MoveIt needs them for time parametrization. They were chosen conservatively to work in most use
# cases. For specific applications, higher values might lead to better execution performance.

/**:
  ros__parameters:
    robot_description_planning:
      # joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

      # For beginners, we downscale velocity and acceleration limits.
      # You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
      default_velocity_scaling_factor: 0.1
      default_acceleration_scaling_factor: 0.1

      # As MoveIt does not support jerk limits, the acceleration limits provided here are the highest values that guarantee
      # that no jerk limits will be violated. More precisely, applying Euler differentiation in the worst case (from min accel
      # to max accel in 1 ms) the acceleration limits are the ones that satisfy
      # max_jerk = (max_acceleration - min_acceleration) / 0.001

      # Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
      # Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
      joint_limits:
        shoulder_pan_joint:
          has_acceleration_limits: true
          max_acceleration: 5.0
        shoulder_lift_joint:
          has_acceleration_limits: true
          max_acceleration: 5.0
        elbow_joint:
          has_acceleration_limits: true
          max_acceleration: 5.0
        wrist_1_joint:
          has_acceleration_limits: true
          max_acceleration: 5.0
        wrist_2_joint:
          has_acceleration_limits: true
          max_acceleration: 5.0
        wrist_3_joint:
          has_acceleration_limits: true
          max_acceleration: 5.0




