<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro">

  <xacro:macro name="ur_ft" params="
    ur_name:=ur
    ur_type:=ur5x
    tf_prefix
    parent
    *origin
    use_fake_hardware:=false
    fake_sensor_commands:=false
    sim_gazebo:=false
    sim_ignition:=false
    headless_mode:=false
    initial_positions
    simulation_controllers"
    >

    <!-- import main macro -->
    <xacro:include filename="$(find ur_description)/urdf/ur_macro.xacro"/>
    <xacro:include filename="$(find robotiq_description)/urdf/ur_to_robotiq_adapter.urdf.xacro" />
    <xacro:include filename="$(find robotiq_ft_sensor_description)/urdf/robotiq_ft300.urdf.xacro" />
    

    <!-- property -->
    <xacro:property name="joint_limits_parameters_file" value="$(find ur_description)/config/${ur_type}/joint_limits.yaml"/>
    <xacro:property name="kinematics_parameters_file" value="$(find ur_description)/config/${ur_type}/default_kinematics.yaml"/>
    <xacro:property name="physical_parameters_file" value="$(find ur_description)/config/${ur_type}/physical_parameters.yaml"/>
    <xacro:property name="visual_parameters_file" value="$(find ur_description)/config/${ur_type}/visual_parameters.yaml"/>
    <xacro:property name="transmission_hw_interface" value=""/>
    <xacro:property name="safety_limits" value="false"/>
    <xacro:property name="safety_pos_margin" value="0.15"/>
    <xacro:property name="safety_k_position" value="20"/>
    <!-- ros2_control related parameters -->
    <xacro:property name="headless_mode" value="false" />
    <xacro:property name="robot_ip" value="0.0.0.0" />
    <xacro:property name="script_filename" value=""/>
    <xacro:property name="output_recipe_filename" value=""/>
    <xacro:property name="input_recipe_filename" value=""/>
    <xacro:property name="reverse_ip" value="0.0.0.0"/>
    <xacro:property name="script_command_port" value="50004"/>
    <xacro:property name="reverse_port" value="50001"/>
    <xacro:property name="script_sender_port" value="50002"/>
    <xacro:property name="trajectory_port" value="50003"/>
    <!--   tool communication related parameters-->
    <xacro:property name="use_tool_communication" value="false" />
    <xacro:property name="tool_voltage" value="0" />
    <xacro:property name="tool_parity" value="0" />
    <xacro:property name="tool_baud_rate" value="115200" />
    <xacro:property name="tool_stop_bits" value="1" />
    <xacro:property name="tool_rx_idle_chars" value="1.5" />
    <xacro:property name="tool_tx_idle_chars" value="3.5" />
    <xacro:property name="tool_device_name" value="/tmp/ttyUR" />
    <xacro:property name="tool_tcp_port" value="54321" />


    <!-- arm -->
    <xacro:ur_robot
      name="${ur_name}"
      tf_prefix="${tf_prefix}"
      parent="${parent}" 
      joint_limits_parameters_file="${joint_limits_parameters_file}"
      kinematics_parameters_file="${kinematics_parameters_file}"
      physical_parameters_file="${physical_parameters_file}"
      visual_parameters_file="${visual_parameters_file}"
      transmission_hw_interface="${transmission_hw_interface}"
      safety_limits="${safety_limits}"
      safety_pos_margin="${safety_pos_margin}"
      safety_k_position="${safety_k_position}"
      use_fake_hardware="${use_fake_hardware}"
      fake_sensor_commands="${fake_sensor_commands}"
      sim_gazebo="${sim_gazebo}"
      sim_ignition="${sim_ignition}"
      headless_mode="${headless_mode}"
      initial_positions="${xacro.load_yaml(initial_positions)}"
      use_tool_communication="${use_tool_communication}"
      tool_voltage="${tool_voltage}"
      tool_parity="${tool_parity}"
      tool_baud_rate="${tool_baud_rate}"
      tool_stop_bits="${tool_stop_bits}"
      tool_rx_idle_chars="${tool_rx_idle_chars}"
      tool_tx_idle_chars="${tool_tx_idle_chars}"
      tool_device_name="${tool_device_name}"
      tool_tcp_port="${tool_tcp_port}"
      robot_ip="${robot_ip}"
      script_filename="${script_filename}"
      output_recipe_filename="${output_recipe_filename}"
      input_recipe_filename="${input_recipe_filename}"
      reverse_port="${reverse_port}"
      script_sender_port="${script_sender_port}"
      reverse_ip="${reverse_ip}"
      script_command_port="${script_command_port}"
      trajectory_port="${trajectory_port}"
      >
      <xacro:insert_block name="origin" />          <!-- position robot in the parent link -->
    </xacro:ur_robot>

    <xacro:robotiq_ft300 parent="${tf_prefix}tool0" prefix="${tf_prefix}" sim_gazebo="${sim_gazebo}">
      <origin xyz="0 0 0" rpy="0 0 0"/> 
    </xacro:robotiq_ft300>

    <!-- FORCE REFERENCE FRAME _______________________________________________________________________________
    As specified in the documentation:
    - The Z axis passes through the center of the depression with positive direction in the tool direction.
    - The X axis traces a symmetric line centered on the connector; the positive direction
        points the opposite way away from the connector.
    - The Y axis uses the right hand thumb rule according to X-Z. -->
    <joint name="${tf_prefix}ft300_sensor_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 ${pi} ${-pi/2}" />
      <parent link="${tf_prefix}ft300_sensor" />
      <child link="${tf_prefix}tip_link" />
    </joint>

    <xacro:property name="cylinder_radius" value="0.015"/>
    <xacro:property name="cylinder_length" value="0.06"/>
    <xacro:property name="cylinder_mass" value="1.0"/>
    <link name="${tf_prefix}tip_link">
      <collision>
        <origin xyz="0 0 ${cylinder_length/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${cylinder_radius}" length="${cylinder_length}"/>
        </geometry>
        <material name="tip_link_color">
          <color rgba="0.2 0.2 0.2 1.0"/>
        </material>
      </collision>
      <visual>
        <origin xyz="0 0 ${cylinder_length/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${cylinder_radius}" length="${cylinder_length}"/>
        </geometry>
        <matertial name="tip_link_color">
          <color rgba="0.2 0.2 0.6 1.0"/>
        </matertial>
      </visual>
      <inertial>
        <origin xyz="0 0 ${cylinder_length/2}" rpy="0 0 0"/>
        <mass value="${cylinder_mass}"/>
        <inertia
          ixx="${1/12 * cylinder_mass * (3 * cylinder_radius*cylinder_radius + cylinder_length*cylinder_length)}"
          ixy="0.0"
          ixz="0.0"
          iyy="${1/12 * cylinder_mass * (3 * cylinder_radius*cylinder_radius + cylinder_length*cylinder_length)}"
          iyz="0.0"
          izz="${1/2 * cylinder_mass * cylinder_radius*cylinder_radius}"/>      
      </inertial>
    </link>

    <link name="${tf_prefix}tip_link_end">
    </link>

    <joint name="${tf_prefix}tip_link_end_joint" type="fixed">
      <origin xyz="0 0 ${cylinder_length}" rpy="0 0 0" />
      <parent link="${tf_prefix}tip_link" />
      <child link="${tf_prefix}tip_link_end" />
    </joint>

    <xacro:if value="${sim_gazebo}">
        <gazebo reference="${tf_prefix}ft300_sensor_joint">
          <disableFixedJointLumping>true</disableFixedJointLumping>
          <provideFeedback>true</provideFeedback>
        </gazebo>
        <!-- gazebo plugin for ft sensor 
        This is a controller that simulates a 6 dof force and torque sensor on link or joint.
        For joints, the wrench is reported in the joint child link frame and the
        measure direction is child-to-parent link. (Force and Torque Feed Back Ground Truth)
        If <body_name> is specified, the plugin acts as sensor on a link, otherwise if
        <joint_name> is specified, it acts as a sensor on a joint -->
        <gazebo>
            <plugin name="${tf_prefix}gazebo_ros_ft_sensor" filename="libgazebo_ros_ft_sensor.so">
              <ros>
                <!-- Add a namespace -->
                <namespace>/${tf_prefix}robotiq_ft300</namespace>
                <!-- Remap the default topic -->
                <!-- <remapping>wrench:=wrench_demo</remapping> -->
              </ros>
              <!-- Joint name -->
              <joint_name>${tf_prefix}ft300_sensor_joint</joint_name>
              <!-- Update rate in Hz, defaults to 0.0, which means as fast as possible -->
              <update_rate>50</update_rate>
              <!-- Standard deviation of the noise to be added to the reported wrench messages. -->
              <gaussian_noise>0.01</gaussian_noise>
        
            </plugin>

        </gazebo>

    </xacro:if>


  </xacro:macro>
</robot>
